// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MemberInfoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *MemberInfoRequest) Reset()                    { *m = MemberInfoRequest{} }
func (m *MemberInfoRequest) String() string            { return proto1.CompactTextString(m) }
func (*MemberInfoRequest) ProtoMessage()               {}
func (*MemberInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MemberInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MemberInfoResponse struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age   int64    `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	City  string   `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Likes []string `protobuf:"bytes,4,rep,name=likes" json:"likes,omitempty"`
}

func (m *MemberInfoResponse) Reset()                    { *m = MemberInfoResponse{} }
func (m *MemberInfoResponse) String() string            { return proto1.CompactTextString(m) }
func (*MemberInfoResponse) ProtoMessage()               {}
func (*MemberInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MemberInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberInfoResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *MemberInfoResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *MemberInfoResponse) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func init() {
	proto1.RegisterType((*MemberInfoRequest)(nil), "proto.MemberInfoRequest")
	proto1.RegisterType((*MemberInfoResponse)(nil), "proto.MemberInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MemberService service

type MemberServiceClient interface {
	GetMember(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) GetMember(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error) {
	out := new(MemberInfoResponse)
	err := grpc.Invoke(ctx, "/proto.MemberService/GetMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberService service

type MemberServiceServer interface {
	GetMember(context.Context, *MemberInfoRequest) (*MemberInfoResponse, error)
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MemberService/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMember(ctx, req.(*MemberInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMember",
			Handler:    _MemberService_GetMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}

func init() { proto1.RegisterFile("member.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0x4a, 0xc4, 0x40,
	0x0c, 0x86, 0x69, 0xbb, 0x2b, 0x34, 0xac, 0x8b, 0x86, 0x3d, 0x8c, 0x8b, 0x87, 0x52, 0x2f, 0x3d,
	0x6d, 0x41, 0x1f, 0x42, 0x3c, 0x78, 0xa9, 0xe0, 0x7d, 0xba, 0x8d, 0x25, 0xd8, 0x99, 0xd4, 0xce,
	0x28, 0x88, 0x78, 0xf1, 0x15, 0x7c, 0x34, 0x5f, 0xc1, 0x07, 0x91, 0xce, 0x78, 0x10, 0xdc, 0x53,
	0xfe, 0x24, 0x5f, 0xc8, 0x07, 0x2b, 0x43, 0xa6, 0xa5, 0x69, 0x37, 0x4e, 0xe2, 0x05, 0x97, 0xa1,
	0x6c, 0xcf, 0x7b, 0x91, 0x7e, 0xa0, 0x5a, 0x8f, 0x5c, 0x6b, 0x6b, 0xc5, 0x6b, 0xcf, 0x62, 0x5d,
	0x84, 0xca, 0x0b, 0x38, 0xbd, 0x0d, 0x47, 0x37, 0xf6, 0x41, 0x1a, 0x7a, 0x7a, 0x26, 0xe7, 0x71,
	0x0d, 0x29, 0x77, 0x2a, 0x29, 0x92, 0x2a, 0x6f, 0x52, 0xee, 0xca, 0x0e, 0xf0, 0x2f, 0xe4, 0x46,
	0xb1, 0x8e, 0x10, 0x61, 0x61, 0xb5, 0xa1, 0x5f, 0x2e, 0x64, 0x3c, 0x81, 0x4c, 0xf7, 0xa4, 0xd2,
	0x22, 0xa9, 0xb2, 0x66, 0x8e, 0x33, 0xb5, 0x67, 0xff, 0xaa, 0xb2, 0x48, 0xcd, 0x19, 0x37, 0xb0,
	0x1c, 0xf8, 0x91, 0x9c, 0x5a, 0x14, 0x59, 0x95, 0x37, 0xb1, 0xb9, 0xec, 0xe1, 0x38, 0x7e, 0xb9,
	0xa3, 0xe9, 0x85, 0xf7, 0x84, 0xf7, 0x90, 0x5f, 0x93, 0x8f, 0x33, 0x54, 0x51, 0x78, 0xf7, 0xcf,
	0x76, 0x7b, 0x76, 0x60, 0x13, 0x15, 0xcb, 0xcd, 0xc7, 0xd7, 0xf7, 0x67, 0xba, 0xc6, 0x55, 0x6d,
	0x0c, 0xb5, 0x34, 0xd5, 0x6f, 0xdc, 0xbd, 0xb7, 0x47, 0x81, 0xbf, 0xfa, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x8a, 0xf8, 0xf0, 0x2f, 0x01, 0x00, 0x00,
}
